language: python
python:
- '2.7'
install:
- pip install --upgrade pip
- export PATH=$HOME/.local/bin:$PATH
- pip install --only-binary=numpy numpy
- pip install -U boto3 pandas requests BeautifulSoup4
script: make manual
deploy:
  provider: s3
  on:
    all_branches: true
  access_key_id:
    secure: fioXUYRC2rCPTFf4KElNRaXNrhl8oUE2OEPRd+AtAsv754Lsv4Y7I3rVrYLAEnMACtkGyAycxwDcg3VbWGz6M3gtBgwQJw25/bJYCEP780k3Ul/evmMwUduv83Cdr/vL8a3bxRkHIQBp0JU7TIEsAaxz9Us7a0FfY9eu4q7Jerg4FaIcZAyEZfpqfRkcVNDKpaKbgrSJjrawUYX8pIZ1/muLVL1Z4P36gtSwyZ89+aRUyAjnTP7YPaWAN0lECsfaoavv993rFgXj6xhdN8w4B55CX2SMJUDnc6LQ7c/xt6+hImf0aWTZoqy9rNuKJb65ioqJrRLqYK8072lxVvYL4oL7FjOy4LqQ9lYd0kE0mz+0OKDDdmO6KnKbLhjunBCibm+eue6JtZK8ZV1H7FcLB97BlFNmXZS/yW+WjfyihZPLPs+SSG+3/GX0SilvbyZ4r9LNISbfie1K3YqWjnezQgqnx8XfC3ZUH/8P8ye9iQCui9xLkKXDSaSzE7IpfqRXKCto9ipsorqxH8SmChVix0oZW4RrZz3zsUyRBOUUysO3T/8Hsy2A5MoHoNmQNO3T4cxUtsz0eyU029fyeIgowcrT2rCLG2Ju6hnk0u00BelRT+12qpm62Oz+B3RuLdeBnz8hYQoNlFZBzUvLI/aJ9YmJIiKqIF+51I2Hlpk7u9Q=
  secret_access_key:
    secure: OWkwqpIIqRCAwg5UzNcamxhovVE7JFI/yBpV4Mxu8jR9GOG7AhjgUOKRxUuNb14LxNsgEHWBcX+ZdQoySK1Ra8WYyB447CVRtk7q0nBsDS1y8AjHEftfOpJym3wt+PimAOZkhNtW8aHdLf7XTZuHI7Lh4qRWL+5NCmyYidg+NcV4tslanP/7J3vZQLpujxHtiTtEg90M6YHeyDQpMMbcvmN2zWqO2upB1rrMWoxlHEcjnhQQV537YO5x/AcoVt0PaXCwbbPa9Pj1jnul/9Voc3Ra7HGtHqrQJAb0Ja+82ikPRUEgLsrLIqEXmSsx7f4H+iRBJLAUdAiakVD5T9T4VTyN6bRxNgP8+tniUCddcyhch7JQ+IgpAAxvTmKeogHNmNtQfsbcace/b5RVbGBiGZUwvHDqXKv68iq3NON78ucC4g/gqfwXTMv8gnpJ0FZKQmihaEm2x4tCyvaPylA/a+ZZuWlKTOSIvXe9DbXdEn0V3hp97U4FXs/xfiDcfuQKz+xBbiv3cY6ZjzOQhgEVY5YpTOAXPMQGy3husUn3SrR9erfc+a5G46CTqv22ghaipacqr1QK76ZQ/jTO8fUPcVwS+p0JS6ejZloXIlQZ0QxQma3HZ33KBp81XQj4T+tq5htpgl63OMOkmh7vCDvERIlygLscED2Oi0gKeE5Gx08=
  bucket:
    secure: fB/BDTrmTFfdwxpcDIiLVPgN5mKJaddF26tSGL+MwLl3TZEcNVnOzAb3RkssztotLI3WVGv0uoMKbI/pFYx/b0vy7/vpMxo93IDiGdQoF/QAsoHx3hIRswVC8Ev1ZZWkgcT+WeOW4b4ebrHyU4l+ZwCgUuiBQtFR1jDhuVFMr+byx7aS3EPgslYy9TS1MS7QYDv/5YyfjSVV2Vmbu+noqxMKHQxk3nzOlyG0Wnn3JknslpxbVuGnYrwnIN92/gcUlEQA3Fe92f3y9AGAKbiib5RYiNQv84xtN90NS/S7Yyk2whkSmR3++gcoIxp++wBRlOxqLq0vkQCkHZ3V2N7PWALMEUrrLoswB0P5nA/gAg7afD+dyBDUXgQGmA3y43jage0yNm8gvjlsvxI7n5ARLuCATtA3wJLiU6Vbkbky0frDqPkoQVsZCRwSm8wINDE0V2ZqYkdoe+NBMlYFxmTsgAaMv4o4ozrFPh+ge1FXhizjNVLCWoMtWmqdN59csQ2K02F4HfaWdW/bbC26dvCnGk44ZV678cgwuRVnU1rs9d3DU+AtLBh4fKTbEvTSvWNPdP1kAcRjtFxVDTUApymVSjZpNpw/kTtP3cN6Np61HUlYZcaTbFfNc5GCqH+DyW0ocboMQRccCCxW1D8QecUYWsBPLBpGrNu65pbCPIy8P+k=
  upload_dir: lambdas
  server_side_encryption: true
  local_dir: build
  region: us-west-2
  skip_cleanup: true
notifications:
  slack:
    secure: Md3y7O98hZF4bL8ds5JUnS43EqtYPCbXDecSrrrjZu/H0ajBWLgBLonJllam1IY91T8dWvDPfX3keiH79khptglP5cvY5hB6+kjIgiK/C0oYJjdrTH/KEdrL2C9X3m65h6+3kUec3+JF4dZp7iYK2P/sf5ZzYAQjqUAZcRnzKhFe1YSZxQN5Cmb/kX2Q8p3ukek5NXxXOt8jNKCdmHODNG+uiooNWhA7mD9rN5jsHcOQTnkvHpqIyALSsnUL55c8Nzqj30b8T7XtASCKRTNLE4cwiXLMkum/rV8UAmULVKJM9ET1twkcJTerM7obAwjbJj8WF6+brb4SIaWKc7BFQWgTwtQJfBlV8M/eqMRav9kNGQA3KmyGMbAlD8WX5FLibRKrd66iv1Y7ItNWal5SnfK0aXUwwxbK32KlQp4PYwzKn7eCJHZ5g+o7Q34G7GA1yOv0gWcTAdCG2Sbe8YKe8CMXixVMRNYg/o6iicprX9xjo62fQbvZDL1rOMN9ZzGu/kQti3G5E381yv8m94qAj04wfVtR11wiEbH3gm+kyfBIBN3ai1WBEBWlodzgZFiWhisUEkyV6we+sLOSduAa7XzlzyZTiyLb4NzYweFHOTXXEWWUNR4nxLRAePGy5L9TE+efPITu/9ToskemQuU3RaijbEAyaK6tF4VByrs5eMQ=
