[project]
name = "zestimate-lambda"
classifiers = [ "License :: OSI Approved :: MIT License",]
readme="README.md"
dynamic = ["version"]
dependencies = [
  "boto3",
  "logging",
  "pandas",
  "requests",
  "datetime",
  "s3fs"
]
