# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: 
      - master
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv venv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create ZIP
      run: |
        zip -j update-zestimate.zip functions/update-zestimate/${MAIN}
        zip -r update-zestimate.zip ./venv/lib/python3.8/site-packages/*
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Copy deployment ZIP to AWS
      run: |
        aws s3 sync . s3://${{ secrets.BUCKET }}/${{ secrets.PATH }}
    - name: Send message to Slack API
      uses: archive/github-actions-slack@v1.1.0
      id: notify
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
        slack-channel: test
        slack-text: Hello! Event "${{ github.event_name }}" in "${{ github.repository }}" 🤓
    - name: Result from "Send Message"
      run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
